# Generated by Django 5.1.2 on 2024-10-29 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('lieu', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('contact1', models.IntegerField()),
                ('contact2', models.IntegerField()),
                ('infos_supp', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise')], max_length=50)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_devis', models.CharField(max_length=250)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateField(auto_now=True)),
                ('statut', models.CharField(choices=[('VALIDE', 'VALIDE'), ('REFUSE', 'REFUSE')], max_length=250)),
                ('montant_avec_taxe', models.FloatField()),
                ('montant_ht', models.FloatField()),
                ('montant_total', models.FloatField()),
                ('id_client', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion.client')),
                ('date_creation', models.DateField()),
                ('immatriculation', models.CharField(max_length=250)),
            ],
            bases=('gestion.client',),
        ),
        migrations.CreateModel(
            name='Particulier',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion.client')),
                ('prenom', models.CharField(max_length=250)),
            ],
            bases=('gestion.client',),
        ),
    ]
