# Generated by Django 5.1.2 on 2024-11-09 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devis',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='montant_avec_taxe',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='montant_ht',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='montant_total',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='object_devis',
        ),
        migrations.AddField(
            model_name='devis',
            name='numero',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devis',
            name='objet_devis',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devis',
            name='total_ht',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devis',
            name='total_ttc',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devis',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devis',
            name='date_creation',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='id_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.client'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='statut',
            field=models.CharField(choices=[('valide', 'Devis validé'), ('refuse', 'Devis refusé'), ('en_cours', 'Devis en cours')], default='en_cours', max_length=20),
        ),
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite', models.PositiveIntegerField()),
                ('total_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.devis')),
            ],
        ),
    ]
