# Generated by Django 5.1.2 on 2024-12-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_devis_date_modification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lignedevis',
            old_name='description',
            new_name='designation',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='id',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='tva',
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='total_ttc',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devis',
            name='numero',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='quantite',
            field=models.IntegerField(),
        ),
    ]
