# Generated by Django 5.1.2 on 2024-12-03 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_rename_description_lignedevis_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignedevis',
            name='prix_unitaire_ht',
        ),
    ]
