# Generated by Django 5.1.2 on 2024-12-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_remove_lignedevis_prix_unitaire_ht'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignedevis',
            name='prix_ht',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
