# Generated by Django 5.1.2 on 2024-12-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_lignedevis_prix_ht'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignedevis',
            name='prix_ht',
            field=models.DecimalField(decimal_places=2, max_digits=200),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='total_ht',
            field=models.DecimalField(decimal_places=2, max_digits=200),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='total_ttc',
            field=models.DecimalField(decimal_places=2, max_digits=200),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='tva',
            field=models.DecimalField(decimal_places=2, max_digits=200),
        ),
    ]
