# Generated by Django 5.1.2 on 2024-12-08 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_lignedevis_prix_ht_alter_lignedevis_total_ht_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignedevis',
            name='prix_ht',
        ),
    ]
