# Generated by Django 5.1.2 on 2024-12-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_remove_lignedevis_prix_ht'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignedevis',
            name='prix_ht',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=200),
            preserve_default=False,
        ),
    ]
