# Generated by Django 5.1.2 on 2024-12-08 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_lignedevis_prix_unitaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignedevis',
            name='prix_unitaire',
        ),
    ]
