# Generated by Django 5.1.2 on 2025-01-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_remove_lignedevis_prix_unitaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignedevis',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=200),
            preserve_default=False,
        ),
    ]
