# Generated by Django 5.1.2 on 2025-01-11 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_devis_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devis',
            name='id_user',
        ),
    ]
