# Generated by Django 5.1.2 on 2026-01-03 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_devis_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='contact2',
        ),
    ]
