# Generated by Django 5.1.2 on 2026-01-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_remove_client_contact2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='numero',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
