# Generated by Django 5.1.2 on 2026-01-03 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_alter_devis_numero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devis',
            options={'ordering': ['numero']},
        ),
    ]
